version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "8000:3000"
        volumes: 
            - .:/app
            - /app/node_modules